In [1]:
import numpy as np
import torch_geometric as pyg
from torch_geometric.utils import to_dense_adj

# KarateClub dataset

In [18]:
karateclub = pyg.datasets.KarateClub()[0]

adj = to_dense_adj(karateclub.edge_index).squeeze().numpy().astype(np.int8)
feat = karateclub.x.numpy().astype(np.int8)
label = karateclub.y.numpy().astype(np.int8)

np.save("../data/karateclub/adj.npy", adj)
np.save("../data/karateclub/feat.npy", feat)
np.save("../data/karateclub/label.npy", label)

# Dataset compression
The dataset sizes are reduced by converting the data types to int8. The original data types are float32 / int32.

In [40]:
dataset = "uat"

In [41]:
adj = np.load("../data/" + dataset + "/adj.npy")
np.unique(adj), adj.shape, adj.dtype

(array([0, 1], dtype=int8), (1190, 1190), dtype('int8'))

In [42]:
np.save("../data/" + dataset + "/adj.npy", adj.astype(np.int8))

In [43]:
feat = np.load("../data/" + dataset + "/feat.npy")
np.unique(feat), feat.shape, feat.dtype

(array([0, 1], dtype=int8), (1190, 239), dtype('int8'))

In [44]:
np.save("../data/" + dataset + "/feat.npy", feat.astype(np.int8))

In [48]:
label = np.load("../data/" + dataset + "/label.npy")
np.unique(label), label.shape, label.dtype

(array([0, 1, 2, 3]), (1190,), dtype('int32'))